version: 0.2
phases:
  install:
    commands:
      - echo "Installing OpenJDK 17..."
      - apt-get update
      - apt-get install -y openjdk-17-jdk

  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/*.jar
  discard-paths: yes
